const $=id=>document.getElementById(id);
let running=false,timer;
function steps(n){for(let i=1;i<=4;i++){let e=$(`s${i}`);e.className=i<n?'done':i===n?'active':''}for(let i=1;i<=3;i++)$(`l${i}`).style.background=i<n?'#5f8a70':'#272f37'}
function log(t){let p=document.createElement('p');p.textContent='10:42:'+String(10+document.querySelectorAll('#plog p').length)+ ' '+t;$('plog').appendChild(p);while($('plog').children.length>5)$('plog').removeChild($('plog').firstChild)}
function event(time,title,detail){let box=$('timeline');if(box.dataset.started!=='1'){box.innerHTML='';box.dataset.started='1'}let e=document.createElement('div');e.className='event';e.innerHTML=`<time>${time}</time><div class="dot"></div><article><b>${title}</b>${detail}</article>`;box.appendChild(e)}
function anr(){if(running)return;running=true;$('anr').disabled=true;$('title').textContent='Capturing incident…';$('fps').textContent='4';log('ANR trigger requested');setTimeout(()=>event('10:42:16.2','User tapped “Load”','Interaction recorded by SnapTrace.'),250);setTimeout(()=>{event('10:42:17.1','Main thread blocked','Blocking database operation detected.');$('m1').textContent='480 ms';$('m2').textContent='2.8 s';$('m3').textContent='780 MB';$('m4').textContent='2.8 s';$('fps').textContent='2';log('Frame time spike: 480ms')},800);setTimeout(()=>{event('10:42:18.0','ANR detected','Application stopped responding.');log('ANR captured');$('title').textContent='Incident captured';transfer()},1450)}
function transfer(){steps(2);$('transfer').textContent='Packaging logs, stack trace and performance evidence…';let p=0;timer=setInterval(()=>{p+=10;$('bar').style.width=p+'%';$('pct').textContent=p+'%';if(p===30)$('transfer').textContent='Sending incident.zip through Office Kit…';if(p===75)$('transfer').textContent='Laptop received incident bundle…';if(p>=100){clearInterval(timer);$('transfer').textContent='Incident bundle received on laptop.';setTimeout(analyze,400)}},90)}
function analyze(){steps(3);$('title').textContent='AI analyzing evidence…';$('confidence').textContent='Analyzing';$('diag').innerHTML='<div class="root"><label>PROCESSING</label><h4>Correlating logs, stack trace and performance signals…</h4><p>Building an evidence-backed incident timeline.</p></div>';$('evidence').innerHTML='<div class="evi">✓ <b>Logcat</b> — received</div><div class="evi">✓ <b>Stack trace</b> — parsed</div><div class="evi">✓ <b>Performance metrics</b> — correlated</div>';setTimeout(diagnose,1000)}
function diagnose(){steps(4);$('title').textContent='Root cause identified';$('confidence').textContent='94% confidence';$('diag').innerHTML='<div class="root"><label>MOST LIKELY ROOT CAUSE</label><h4>Blocking database operation on the UI thread</h4><p>SnapTrace correlated the main-thread stall, frame-time spike and stack trace immediately before the ANR.</p></div>';$('evidence').innerHTML='<div class="evi">• Main thread blocked for <b>2.8 seconds</b></div><div class="evi">• Frame time peaked at <b>480 ms</b></div><div class="evi">• Stack trace points to <b>UserRepository.loadUsers()</b></div><div class="evi">• Database call occurred immediately before the freeze</div>';$('fix').textContent='Move the database operation off the main thread and update the UI asynchronously.';$('code').textContent='// before\nusers = database.getUsers();\n\n// suggested\nexecutor.execute(() -> {\n  List<User> users = database.getUsers();\n  runOnUiThread(() -> render(users));\n});';$('anr').disabled=false;running=false}
function verify(){$('verify').disabled=true;$('verify').textContent='Verifying…';setTimeout(()=>{$('verifybox').style.display='block';$('verify').textContent='Fix verified';$('title').textContent='Incident resolved'},900)}
function reset(){clearInterval(timer);running=false;$('title').textContent='Ready to capture';$('fps').textContent='60';$('timeline').dataset.started='0';$('timeline').textContent='Trigger the ANR on the phone to begin capture.';['m1','m2','m3','m4'].forEach(x=>$(x).textContent='—');$('bar').style.width='0';$('pct').textContent='0%';$('transfer').textContent='Waiting for an incident bundle…';$('diag').className='empty';$('diag').textContent='Run an incident to generate an evidence-backed diagnosis.';$('confidence').textContent='—';$('evidence').className='empty';$('evidence').textContent='Logs, stack trace and metrics will appear here.';$('fix').textContent='SnapTrace will generate a concrete remediation after analysis.';$('code').textContent='// waiting for incident analysis';$('verifybox').style.display='none';$('verify').disabled=false;$('verify').textContent='Verify fix';steps(1)}
$('anr').onclick=anr;$('verify').onclick=verify;$('reset').onclick=reset;$('crash').onclick=()=>alert('Phase 1 demo focuses on ANR/UI freeze. Crash capture is part of the next build.');reset();